<a href="https://colab.research.google.com/github/KeerthiErnapu/FML/blob/main/Multivariate_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as pyplt


In [8]:

data=pd.read_csv('/50_Startups.csv')
print(data)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       

In [9]:
data.corr()

R&D Spend  Administration  Marketing Spend    Profit
R&D Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

In [10]:
x=data.drop('Profit',axis=1).values
x=data.drop('State',axis=1).values
y=data['Profit'].values
print(x)

[[165349.2  136897.8  471784.1  192261.83]
 [162597.7  151377.59 443898.53 191792.06]
 [153441.51 101145.55 407934.54 191050.39]
 [144372.41 118671.85 383199.62 182901.99]
 [142107.34  91391.77 366168.42 166187.94]
 [131876.9   99814.71 362861.36 156991.12]
 [134615.46 147198.87 127716.82 156122.51]
 [130298.13 145530.06 323876.68 155752.6 ]
 [120542.52 148718.95 311613.29 152211.77]
 [123334.88 108679.17 304981.62 149759.96]
 [101913.08 110594.11 229160.95 146121.95]
 [100671.96  91790.61 249744.55 144259.4 ]
 [ 93863.75 127320.38 249839.44 141585.52]
 [ 91992.39 135495.07 252664.93 134307.35]
 [119943.24 156547.42 256512.92 132602.65]
 [114523.61 122616.84 261776.23 129917.04]
 [ 78013.11 121597.55 264346.06 126992.93]
 [ 94657.16 145077.58 282574.31 125370.37]
 [ 91749.16 114175.79 294919.57 124266.9 ]
 [ 86419.7  153514.11      0.   122776.86]
 [ 76253.86 113867.3  298664.47 118474.03]
 [ 78389.47 153773.43 299737.29 111313.02]
 [ 73994.56 122782.75 303319.26 110352.25]
 [ 67532.53

In [11]:

y=y.reshape(-1,1)
print(y)

[[192261.83]
 [191792.06]
 [191050.39]
 [182901.99]
 [166187.94]
 [156991.12]
 [156122.51]
 [155752.6 ]
 [152211.77]
 [149759.96]
 [146121.95]
 [144259.4 ]
 [141585.52]
 [134307.35]
 [132602.65]
 [129917.04]
 [126992.93]
 [125370.37]
 [124266.9 ]
 [122776.86]
 [118474.03]
 [111313.02]
 [110352.25]
 [108733.99]
 [108552.04]
 [107404.34]
 [105733.54]
 [105008.31]
 [103282.38]
 [101004.64]
 [ 99937.59]
 [ 97483.56]
 [ 97427.84]
 [ 96778.92]
 [ 96712.8 ]
 [ 96479.51]
 [ 90708.19]
 [ 89949.14]
 [ 81229.06]
 [ 81005.76]
 [ 78239.91]
 [ 77798.83]
 [ 71498.49]
 [ 69758.98]
 [ 65200.33]
 [ 64926.08]
 [ 49490.75]
 [ 42559.73]
 [ 35673.41]
 [ 14681.4 ]]


In [12]:
print(x)

[[165349.2  136897.8  471784.1  192261.83]
 [162597.7  151377.59 443898.53 191792.06]
 [153441.51 101145.55 407934.54 191050.39]
 [144372.41 118671.85 383199.62 182901.99]
 [142107.34  91391.77 366168.42 166187.94]
 [131876.9   99814.71 362861.36 156991.12]
 [134615.46 147198.87 127716.82 156122.51]
 [130298.13 145530.06 323876.68 155752.6 ]
 [120542.52 148718.95 311613.29 152211.77]
 [123334.88 108679.17 304981.62 149759.96]
 [101913.08 110594.11 229160.95 146121.95]
 [100671.96  91790.61 249744.55 144259.4 ]
 [ 93863.75 127320.38 249839.44 141585.52]
 [ 91992.39 135495.07 252664.93 134307.35]
 [119943.24 156547.42 256512.92 132602.65]
 [114523.61 122616.84 261776.23 129917.04]
 [ 78013.11 121597.55 264346.06 126992.93]
 [ 94657.16 145077.58 282574.31 125370.37]
 [ 91749.16 114175.79 294919.57 124266.9 ]
 [ 86419.7  153514.11      0.   122776.86]
 [ 76253.86 113867.3  298664.47 118474.03]
 [ 78389.47 153773.43 299737.29 111313.02]
 [ 73994.56 122782.75 303319.26 110352.25]
 [ 67532.53

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.70,test_size=0.30)

In [14]:
reg = linear_model.LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [15]:
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
y_predict=reg.predict(x_train)
print(f'MAE = {mean_absolute_error(y_train, y_predict)}')
print(f'MSE = {mean_squared_error(y_train, y_predict)}')
print(f'RMSE = {np.sqrt(mean_squared_error(y_train, y_predict))}')
print(f'R_2 = {r2_score(y_train, y_predict)}')

MAE = 4.3915601314178534e-11
MSE = 3.0479005862082475e-21
RMSE = 5.520779461460354e-11
R_2 = 1.0


In [17]:
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
y_testpre=reg.predict(x_test)
print(f'MAE = {mean_absolute_error(y_test, y_testpre)}')
print(f'MSE = {mean_squared_error(y_test, y_testpre)}')
print(f'RMSE = {np.sqrt(mean_squared_error(y_test, y_testpre))}')
print(f'R_2 = {r2_score(y_test, y_testpre)}')

MAE = 5.335702250401179e-11
MSE = 3.96693763630764e-21
RMSE = 6.298362990736275e-11
R_2 = 1.0


In [20]:
from sklearn.linear_model import Lasso
reg = Lasso(alpha = 0.1)
reg.fit(x_train, y_train)

Lasso(alpha=0.1)

In [21]:
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
y_pred = reg.predict(x_train)
print(f'Performance of the model on training data :\n')
print(f'MAE = {mean_absolute_error(y_train, y_pred)}')
print(f'MSE = {mean_squared_error(y_train, y_pred)}')
print(f'RMSE = {np.sqrt(mean_squared_error(y_train, y_pred))}')
print(f'R_2 = {r2_score(y_train, y_pred)}')

Performance of the model on training data :

MAE = 12.400265807697672
MSE = 255.2792939879051
RMSE = 15.977462063416239
R_2 = 0.9999998584991217


In [22]:
y_predt = reg.predict(x_test)
print(f'Performance of the model on test data :\n')
print(f'MAE = {mean_absolute_error(y_test, y_predt)}')
print(f'MSE = {mean_squared_error(y_test, y_predt)}')
print(f'RMSE = {np.sqrt(mean_squared_error(y_test, y_predt))}')
print(f'R_2 = {r2_score(y_test, y_predt)}')
     

Performance of the model on test data :

MAE = 10.248189126501286
MSE = 168.6443500043973
RMSE = 12.986313949862652
R_2 = 0.999999842606631


In [23]:
reg.score(x_test, y_test)

0.999999842606631